kind: pipeline
name: default

workspace:
  base: /workspace
  path: shared

steps:
- name: pull-and-save-image
  image: mesosphere/aws-cli
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
  commands:
    - apk add --update docker
    - echo $(aws ecr get-login) | docker login --username AWS --password-stdin 312388070267.dkr.ecr.eu-north-1.amazonaws.com
    - docker pull 312388070267.dkr.ecr.eu-north-1.amazonaws.com/rshiny-repo:latest
    - docker save -o /workspace/shared/image.tar 312388070267.dkr.ecr.eu-north-1.amazonaws.com/rshiny-repo:latest

volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock




