kind: pipeline
name: default

workspace:
  base: /workspace
  path: shared

steps:
- name: Pull step
  image: kudato/drone-ecr-pull
  volumes:
  - name: docker
    path: /var/run/docker.sock
  settings:
    region: us-east-1
    access_key:
      from_secret: AWS_ACCESS_KEY_ID
    secret_key:
      from_secret: AWS_SECRET_ACCESS_KEY
    images: [
      "312388070267.dkr.ecr.eu-north-1.amazonaws.com/rshiny-repo:latest",
    ]
  

- name: save-docker-image
  image: docker:19.03
  volumes:
    - name: dockersock
      path: /var/run/docker.sock
  commands:
    - docker save -o /workspace/shared/image.tar 312388070267.dkr.ecr.eu-north-1.amazonaws.com/rshiny-repo:latest

# ... rest of the pipeline ...

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock



