kind: pipeline
name: default

workspace:
  base: /workspace
  path: shared

steps:
- name: pull-and-save-image
  image: python:3.8-alpine
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
    S3_BUCKET:
      from_secret: AWS_S3_BUCKET
  commands:
    - apk add --update docker
    - apk add --update python3 py3-pip
    - pip3 install --upgrade pip
    - pip3 install awscli
    - echo $(aws ecr get-login-password --region eu-north-1) | docker login --username AWS --password-stdin 312388070267.dkr.ecr.eu-north-1.amazonaws.com
    - docker pull 312388070267.dkr.ecr.eu-north-1.amazonaws.com/rshiny-repo:latest
    - docker save -o /workspace/shared/image.tar 312388070267.dkr.ecr.eu-north-1.amazonaws.com/rshiny-repo:latest
    - aws s3 cp /workspace/shared/image.tar s3://S3_BUCKET/image.tar/

volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock
