kind: pipeline
name: default

workspace:
  base: /workspace
  path: shared

steps:
- name: pull-image-from-ecr
  image: docker:19.03
  volumes:
    - name: dockersock
      path: /var/run/docker.sock
  commands:
    - docker login -u AWS -p $(aws ecr get-login-password --region eu-north-1) 312388070267.dkr.ecr.eu-north-1.amazonaws.com/rshiny-repo
    - docker pull 312388070267.dkr.ecr.eu-north-1.amazonaws.com/rshiny-repo:latest

- name: save-docker-image
  image: docker:19.03
  volumes:
    - name: dockersock
      path: /var/run/docker.sock
  commands:
    - docker save -o /workspace/shared/image.tar 312388070267.dkr.ecr.eu-north-1.amazonaws.com/rshiny-repo:latest

# ... rest of the pipeline ...

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock



